# Generated by Django 5.0.3 on 2024-04-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_facebook_profile_instagram'),
        ('art', '0002_alter_artpiece_art_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='artpieces',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='art.artpiece'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
    ]
