# Generated by Django 5.0.3 on 2024-03-27 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPiece',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('art_piece', models.URLField()),
                ('artist', models.CharField(blank=True, max_length=30, null=True)),
                ('type_of_artwork', models.CharField(blank=True, choices=[('Picture', 'Picture'), ('Drawing', 'Drawing'), ('Sculpture', 'Sculpture'), ('Other', 'Other')], max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
