# Generated by Django 5.0.3 on 2024-04-02 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_artpiece_id_alter_artpiece_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
