# Generated by Django 5.0.3 on 2024-04-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_alter_artpiece_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
